Version: '3'
services:
    slice1:
        image: mariadb:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - ./sql/shrd1:/docker-entrypoint-initdb.d
        command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=>
        ports:
            - "4001:3306"

    lamb:
        image: mariadb:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - ./sql/shrd1:/docker-entrypoint-initb.d
        command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=>
        ports:
            - "4002:3306"
            
    slice2:
        image: mariadb:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - ./sql/shrd2:/docker-entrypoint-initdb.d
        command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=>
        ports:
            - "4003:3306"
            
    maxscale:
        image: mariadb/maxscale:latest
        depends_on:
            - lamb
            - slice1
            - slice2
        volumes:
            - ./maxscale.cnf.d:/etc/maxscale.cnf.d
        ports:
            - "4000:4000"  # sharded service listener
            - "4006:4006"  # readwrite port
            - "4008:4008"  # readonly port
            - "8989:8989"  # REST API port
            


